apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-docker-secret
spec:
  containers:
  - name: nginx
    image: nginx    
    envFrom:
    - secretRef:
        name: my-registry-secret